-- DML: Insert Data (PostgreSQL-safe)
-- Insert exam: Exam 3
WITH inserted AS (
    INSERT INTO exams (name) VALUES ('Exam 3') RETURNING id
)
INSERT INTO words (exam_id, word, meaning, translation) VALUES ((SELECT id FROM inserted), 'reliable', 'trustworthy', 'אמין')
, ((SELECT id FROM inserted), 'rely on/upon sb/sth', 'help, depend on, need someone for support', 'להסתמך על, להיות תלוי ב, להזדקק ל')
, ((SELECT id FROM inserted), 'request', 'asking for something', 'לבקש, בקשה')
, ((SELECT id FROM inserted), 'research', 'a study, a scientific investigation', 'לחקור, מחקר')
, ((SELECT id FROM inserted), 'researcher', 'scientist', 'חוקר')
, ((SELECT id FROM inserted), 'result', 'what happens in the end', 'תוצאה')
, ((SELECT id FROM inserted), 'resulting', 'cause', 'מביא לתוצאה')
, ((SELECT id FROM inserted), 'review', 'go over and give opinion/ opinion', 'לסקור, סקירה')
, ((SELECT id FROM inserted), 'revise', 'review, study over and make changes', 'לחזור')
, ((SELECT id FROM inserted), 'revision', 'review', 'חזרה על חומר')
, ((SELECT id FROM inserted), 'risk', 'danger/ chance', 'סכנה, סיכון')
, ((SELECT id FROM inserted), 'run out of', 'finish', 'אזל')
, ((SELECT id FROM inserted), 'rural', 'in the countryside, out of the city', 'כפרי')
, ((SELECT id FROM inserted), 'salary', 'money earned from work', 'משכורת')
, ((SELECT id FROM inserted), 'sample', 'a small part, example', 'מדגם, דוגמית')
, ((SELECT id FROM inserted), 'seldom', 'infrequently, not often', 'לעיתים רחוקות')
, ((SELECT id FROM inserted), 'sense', 'reason, good judgement', 'הגיון')
, ((SELECT id FROM inserted), 'sensible', 'logical, smart', 'הגיוני, חכם')
, ((SELECT id FROM inserted), 'set up', 'put in the right place, begin', 'להכין, להקים')
, ((SELECT id FROM inserted), 'set out', 'begin a journey, present', 'לצאת למסע, להציג')
, ((SELECT id FROM inserted), 'significant', 'large amount, important, meaningful', 'משמעותי')
, ((SELECT id FROM inserted), 'significantly', 'in a big or meaningful way', 'באופן משמעותי')
, ((SELECT id FROM inserted), 'significance', 'meaning, importance', 'משמעות')
, ((SELECT id FROM inserted), 'skilled', 'has the ability to do something well', 'מוכשר')
, ((SELECT id FROM inserted), 'skillful', 'has an impressive ability', 'מוכשר')
, ((SELECT id FROM inserted), 'slight', 'a small amount', 'דק, קטן')
, ((SELECT id FROM inserted), 'slightly', 'a little bit', 'בקצת')
, ((SELECT id FROM inserted), 'specialist', 'someone with specific skills', 'מומחה')
, ((SELECT id FROM inserted), 'specialize', 'to study something specific', 'להתמחות')
, ((SELECT id FROM inserted), 'specific', 'certain, exact', 'ספציפי, מסויים')
, ((SELECT id FROM inserted), 'specifically', 'especially', 'באופן ספציפי')
, ((SELECT id FROM inserted), 'specify', 'to say exactly, in detail', 'לפרט')
, ((SELECT id FROM inserted), 'still', 'despite everything', 'עדיין (למרות)')
, ((SELECT id FROM inserted), 'structure', 'shape, design', 'מבנה')
, ((SELECT id FROM inserted), 'study', 'examine, look at, learn; research', 'ללמוד, מחקר')
, ((SELECT id FROM inserted), 'supposed', 'should', 'אמור')
, ((SELECT id FROM inserted), 'surface', 'top or outer layer', 'פני השטח')
, ((SELECT id FROM inserted), 'take advantage of sth', 'make use of something', 'לנצל')
, ((SELECT id FROM inserted), 'thanks to sb/sth', 'because of', 'הודות ל')
, ((SELECT id FROM inserted), 'theoretical', 'the idea of something', 'באופן תאורטי')
, ((SELECT id FROM inserted), 'theory', 'an idea', 'תאוריה')
, ((SELECT id FROM inserted), 'throw away/out sth or throw sth away/out', 'put in the garbage, dispose of', 'לזרוק(לפח)')
, ((SELECT id FROM inserted), 'transport', 'move from place to place', 'שינוע, לשנע')
, ((SELECT id FROM inserted), 'transportation', 'a way of taking something or someone from place to place', 'תחבורה')
, ((SELECT id FROM inserted), 'trash', 'garbage', 'זבל')
, ((SELECT id FROM inserted), 'treatment', 'dealing with, medical care', 'טיפול')
, ((SELECT id FROM inserted), 'unfortunate', 'bad, unlucky', 'לא טוב, מזל רע')
, ((SELECT id FROM inserted), 'unfortunately', 'sadly', 'לצערנו')
, ((SELECT id FROM inserted), 'unhealthy', 'not healthy', 'לא בריא')
, ((SELECT id FROM inserted), 'unique', 'special, one of a kind', 'ייחודי')
, ((SELECT id FROM inserted), 'united', 'together, as one', 'מאוחד')
, ((SELECT id FROM inserted), 'unite', 'to combine', 'לאחד')
, ((SELECT id FROM inserted), 'unity', 'being together as one', 'איחוד')
, ((SELECT id FROM inserted), 'universal', 'true all over the world', 'אונברסלי')
, ((SELECT id FROM inserted), 'universe', 'everything that exists', 'יקום')
, ((SELECT id FROM inserted), 'unknown', 'not known', 'לא יודע')
, ((SELECT id FROM inserted), 'unlike', 'different from', 'לא דומה')
, ((SELECT id FROM inserted), 'unlikely', 'improbable', 'לא סביר')
, ((SELECT id FROM inserted), 'urban', 'related to a city', 'עירוני')
, ((SELECT id FROM inserted), 'variation', 'difference', 'הבדל, מגוון')
, ((SELECT id FROM inserted), 'vary', 'to change', 'לגוון')
, ((SELECT id FROM inserted), 'view', 'a scene you can see', 'נוף')
, ((SELECT id FROM inserted), 'viewer', 'people who watch', 'הצופה')
, ((SELECT id FROM inserted), 'visible', 'can be seen', 'ניתן לראות אותו')
, ((SELECT id FROM inserted), 'vision', 'dream, hope, idea, sight', 'חזון')
, ((SELECT id FROM inserted), 'volume', 'amount', 'כמות')
, ((SELECT id FROM inserted), 'whom', '(used instead of ''who'' as the object of a verb)', 'מי')
, ((SELECT id FROM inserted), 'wildlife', 'wild animals', 'חיות בר')
, ((SELECT id FROM inserted), 'within', 'a limit of time or distance', 'תוך (זמן או מקום)')
, ((SELECT id FROM inserted), 'worthwhile', 'valuable, worth spending time or money on it', 'שווה, כדאי')
, ((SELECT id FROM inserted), 'would', '(used as the past form of ''will'' to talk about what someone said or thought)', 'היה עושה')
, ((SELECT id FROM inserted), 'above', 'in a higher place', 'מעל')
, ((SELECT id FROM inserted), 'account', 'a report', 'דין וחשבון')
, ((SELECT id FROM inserted), 'acquire', 'to get', 'להשיג, לרכוש')
, ((SELECT id FROM inserted), 'acquisition', 'getting', 'רכישה')
, ((SELECT id FROM inserted), 'age', 'period of history', 'עידן')
, ((SELECT id FROM inserted), 'aged', 'old', 'זקן')
, ((SELECT id FROM inserted), 'agriculture', 'farming', 'חקלאות')
, ((SELECT id FROM inserted), 'agricultural', 'related to farming', 'חקלאי')
, ((SELECT id FROM inserted), 'all of a sudden', 'suddenly', 'לפתע')
, ((SELECT id FROM inserted), 'altogether', 'entirely, completely', 'סך הכל')
, ((SELECT id FROM inserted), 'anxious', 'worried, concerned', 'מוטרד')
, ((SELECT id FROM inserted), 'anxiety', 'a condition of feeling uneasy or worried about what may happen', 'חרדה')
, ((SELECT id FROM inserted), 'apparent', 'clearly visible, obvious', 'נראה לעיין')
, ((SELECT id FROM inserted), 'apparently', 'obviously, seemingly', 'כנראה')
, ((SELECT id FROM inserted), 'appropriate', 'suitable', 'הולם')
, ((SELECT id FROM inserted), 'atmosphere', 'a thin layer of gases surrounding Earth', 'אטמוספרה')
, ((SELECT id FROM inserted), 'automatically', 'gets done without a person''s deliberate control', 'באופן אוטומטי')
, ((SELECT id FROM inserted), 'bad', 'rotting', 'רקוב')
, ((SELECT id FROM inserted), 'be in charge', 'take control, be the leader', 'להיות אחראי על')
, ((SELECT id FROM inserted), 'be situated in/on/by, etc', 'to be in a particular place', 'להיות ממוקם ב')
, ((SELECT id FROM inserted), 'behind', 'slower', 'מאחור')
, ((SELECT id FROM inserted), 'believe in something', 'to think that sth is good or right', 'להאמין ב')
, ((SELECT id FROM inserted), 'blame', 'to say or think that a person or thing is responsible for something bad that has happened', 'להאשים')
, ((SELECT id FROM inserted), 'block', 'not to let pass or see', 'לחסום')
, ((SELECT id FROM inserted), 'brilliant', 'very intelligent', 'מבריק')
, ((SELECT id FROM inserted), 'bring up somebody or bring somebody up', 'to care for a child until it is an adult', 'לגדל (ילד)')
, ((SELECT id FROM inserted), 'calculate', 'to work out by using math', 'לחשב')
, ((SELECT id FROM inserted), 'calculator', 'a small machine that is used for math', 'מחשבון')
, ((SELECT id FROM inserted), 'clothing', 'things you wear', 'ביגוד')
, ((SELECT id FROM inserted), 'competitive', 'wanting to win or to be more successful than other people', 'תחרותי')
, ((SELECT id FROM inserted), 'competitor', 'one who competes against others', 'המתחרה')
, ((SELECT id FROM inserted), 'contemporary', 'current, modern, from the same time', 'בן זמננו')
, ((SELECT id FROM inserted), 'contest', 'competition', 'תחרותי')
, ((SELECT id FROM inserted), 'continent', 'one of the seven large landmasses on the earth', 'יבשת')
, ((SELECT id FROM inserted), 'copy', 'single one (book, paper)', 'עותק')
, ((SELECT id FROM inserted), 'criterion', 'a standard of judgement', 'מדד')
, ((SELECT id FROM inserted), 'cut down sth or cut sth down', 'to reduce', 'לצמצם')
, ((SELECT id FROM inserted), 'decade', 'a period of 10 years', 'עשור')
, ((SELECT id FROM inserted), 'declaration', 'a public statement', 'הצהרה,הכרזה')
, ((SELECT id FROM inserted), 'declare', 'to make known, to state publically', 'להצהיר, להכריז')
, ((SELECT id FROM inserted), 'degree', 'qualification/ unit of measurement', 'מידה, מעלה, תואר')
, ((SELECT id FROM inserted), 'deliver', 'to take [something] to a person or place', 'לבצע משלוח')
, ((SELECT id FROM inserted), 'demanding', 'needing a lot of your time, attention, or effort', 'תובעני')
, ((SELECT id FROM inserted), 'detect', 'to discover', 'לגלות, להבחין')
, ((SELECT id FROM inserted), 'determine', 'to decide', 'לקבוע להחליט')
, ((SELECT id FROM inserted), 'differ', 'to disagree', 'לחלוק על')
, ((SELECT id FROM inserted), 'differ', 'to vary widely', 'להיות שונה')
;

-- Insert exam: Exam 4
WITH inserted AS (
    INSERT INTO exams (name) VALUES ('Exam 4') RETURNING id
)
INSERT INTO words (exam_id, word, meaning, translation) VALUES ((SELECT id FROM inserted), 'disappointed', 'unhappy about the way something turned out', 'מאוכזב')
, ((SELECT id FROM inserted), 'disappointment', 'feeling of sadness because something is not as good as expected', 'אכזבה')
, ((SELECT id FROM inserted), 'divide', 'to separate into two or more parts', 'לחלק')
, ((SELECT id FROM inserted), 'division', 'the act or process of dividing', 'חלוקה')
, ((SELECT id FROM inserted), 'domestic', 'Having to do with the home or home country', 'של בית')
, ((SELECT id FROM inserted), 'done', 'finished or completed', 'עשוי, גמור')
, ((SELECT id FROM inserted), 'double', 'twice as much', 'כפול')
, ((SELECT id FROM inserted), 'economical', 'careful about spending money or using resources', 'חסכני')
, ((SELECT id FROM inserted), 'editor', 'the head of a news organization; person who chooses the articles that will be printed each day', 'עורך (עיתון)')
, ((SELECT id FROM inserted), 'either way', 'in both cases', 'בכל מקרה')
, ((SELECT id FROM inserted), 'element', 'A pure substance made of only one kind of atom', 'יסוד (בטבע)')
, ((SELECT id FROM inserted), 'emerge', 'to come out; appear', 'לבצבץ')
, ((SELECT id FROM inserted), 'emotion', 'the feeling that is produced in response to life experiences', 'רגש')
, ((SELECT id FROM inserted), 'emotional', 'showing strong feelings', 'רגשני')
, ((SELECT id FROM inserted), 'exception', 'something that does not fit into a general rule', 'יוצא מן הכלל')
, ((SELECT id FROM inserted), 'exchange', 'giving up something in order to receive something else', 'חילופין')
, ((SELECT id FROM inserted), 'expected', 'to think something will probably happen', 'צפוי')
, ((SELECT id FROM inserted), 'expedition', 'A long journey by a group to explore or do battle', 'משלחת מחקרית')
, ((SELECT id FROM inserted), 'at the expense of', 'at the cost of', 'על חשבון')
, ((SELECT id FROM inserted), 'expense', 'the cost of goods or services', 'הוצאה')
, ((SELECT id FROM inserted), 'export', 'send (goods or services) to another country for sale.', 'לייצא')
, ((SELECT id FROM inserted), 'expression', 'word or phrase', 'ביטוי')
, ((SELECT id FROM inserted), 'extend', 'to hold out, to stretch, to offer', 'להעניק')
, ((SELECT id FROM inserted), 'extreme', 'the furthest or highest degree of something', 'קיצוני')
, ((SELECT id FROM inserted), 'farther/further', 'more far', 'רחוק יותר')
, ((SELECT id FROM inserted), 'fed up', 'bored or frustrated and unhappy', 'נמאס (לו)')
, ((SELECT id FROM inserted), 'fetch', 'to go after and bring back', 'ללכת להביא משהו/ מישהו')
, ((SELECT id FROM inserted), 'final, semi-final', 'last, end', 'סופי, גמר')
, ((SELECT id FROM inserted), 'fit, fitness', 'healthy', 'בכושר, כושר')
, ((SELECT id FROM inserted), 'generation', 'generation', 'דור')
, ((SELECT id FROM inserted), 'genuine', 'real, authentic', 'אמיתי, מקורי')
, ((SELECT id FROM inserted), 'get rid of something', 'make something go away', 'להיפטר ממשהו')
, ((SELECT id FROM inserted), 'get sth wrong', 'make a mistake', 'לטעות')
, ((SELECT id FROM inserted), 'get worse', 'become bad', 'להתדרדר')
, ((SELECT id FROM inserted), 'give away sth or give sth away', 'לתת משהו למישהו', 'לתת משהו למישהו')
, ((SELECT id FROM inserted), 'go out', 'leave', 'לצאת')
, ((SELECT id FROM inserted), 'hidden', 'not possible to see', 'מחובא')
, ((SELECT id FROM inserted), 'highlight', 'show that something is important', 'להדגיש')
, ((SELECT id FROM inserted), 'historian', 'someone who studies history', 'היסטורין')
, ((SELECT id FROM inserted), 'historic', 'of great importance', 'היסטורי')
, ((SELECT id FROM inserted), 'identical', 'the same', 'זהה')
, ((SELECT id FROM inserted), 'immigration', 'moving from one country to another', 'הגירה')
, ((SELECT id FROM inserted), 'immigrant', 'a person who moves from one country to another', 'מהגר')
, ((SELECT id FROM inserted), 'import', 'bring products into a country', 'לייבא')
, ((SELECT id FROM inserted), 'import', 'the act of bringing products into a country', 'ייבוא')
, ((SELECT id FROM inserted), 'impress', 'make someone admire you', 'להרשים')
, ((SELECT id FROM inserted), 'impression', 'an idea or opinion about someone or something', 'רושם')
, ((SELECT id FROM inserted), 'impressive', 'causing people to admire it', 'מרשים')
, ((SELECT id FROM inserted), 'incredible', 'amazing', 'לא יאומן')
, ((SELECT id FROM inserted), 'incredibly', 'in an amazing way', 'באופן מדהים')
, ((SELECT id FROM inserted), 'indoors', 'inside a building', 'בתוך הבית')
, ((SELECT id FROM inserted), 'infection', 'get sick in a way that spreads', 'זיהום')
, ((SELECT id FROM inserted), 'input', 'opinion', 'דעה')
, ((SELECT id FROM inserted), 'inside', 'feeling', 'בפנים (ברגש)')
, ((SELECT id FROM inserted), 'interact', 'behave and respond', 'לפעול בצורה הדדית')
, ((SELECT id FROM inserted), 'interaction', 'communication', 'אינטראקציה')
, ((SELECT id FROM inserted), 'interpret', 'understand something in your own way', 'לפרש')
, ((SELECT id FROM inserted), 'interrupt', 'stop from speaking', 'להפריע, לקטוע')
, ((SELECT id FROM inserted), 'interruption', 'stopping from speaking', 'הפרעה')
, ((SELECT id FROM inserted), 'involvement', 'the act of taking part in something', 'מעורבות')
, ((SELECT id FROM inserted), 'involved', 'being part of something', 'מעורב')
, ((SELECT id FROM inserted), 'involve', 'to include', 'לערב')
, ((SELECT id FROM inserted), 'issue', 'topic, problem', 'נושא, סוגיה')
, ((SELECT id FROM inserted), 'it looks like/as if/as though', 'it seems that', 'נראה ש...')
, ((SELECT id FROM inserted), 'jam, traffic jam', 'something that is stuck', 'פקק (תנועה)')
, ((SELECT id FROM inserted), 'journalist', 'a writer for a newspaper', 'עיתונאי')
, ((SELECT id FROM inserted), 'judgment', 'The act of judging people and their actions', 'שיפוט')
, ((SELECT id FROM inserted), 'just as bad / good / tall / clever, etc (as sb/sth)', 'bad/good/tall/clever, etc. in the same way', 'רע/טוב/גבוה/פיקח וכו באותה מידה')
, ((SELECT id FROM inserted), 'just', 'fair', 'צודק')
, ((SELECT id FROM inserted), 'justice', 'fairness', 'צדק')
, ((SELECT id FROM inserted), 'keen', 'excited about', 'חד/נלהב')
, ((SELECT id FROM inserted), 'keep', 'delay', 'לעכב')
, ((SELECT id FROM inserted), 'kit', 'a set of things', 'ערכה')
, ((SELECT id FROM inserted), 'learn', 'remember', 'ללמוד, לזכור')
, ((SELECT id FROM inserted), 'lecture', 'speech/ give a speech', 'הרצאה, להרצות')
, ((SELECT id FROM inserted), 'light, in light of', 'illuminate', 'להדליק, לאור...')
, ((SELECT id FROM inserted), 'living', 'to earn money', 'פרנסה')
, ((SELECT id FROM inserted), 'logical, logic', 'something the mind can understand', 'הגיוני, הגיון')
, ((SELECT id FROM inserted), 'look forward to something/doing something', 'be excited about something in the future', 'מצפה ל...')
, ((SELECT id FROM inserted), 'lower', 'to make something not as high', 'להנמיך')
, ((SELECT id FROM inserted), 'make sense', 'be logical', 'להיות הגיוני')
, ((SELECT id FROM inserted), 'make up something or make something up, made up of something', 'to include', 'להיות מורכב מ')
, ((SELECT id FROM inserted), 'make up your mind or make your mind up', 'to decide', 'לקבל החלטה')
, ((SELECT id FROM inserted), 'mend', 'to fix', 'לתקן')
, ((SELECT id FROM inserted), 'mixture', 'things combined', 'תערובת')
, ((SELECT id FROM inserted), 'monthly', 'every month', 'חודשי')
, ((SELECT id FROM inserted), 'mystery, mysterious', 'something that is not understood', 'תעלומה, מסתורי')
, ((SELECT id FROM inserted), 'name', 'say the name of, mention', 'לתת שם, לציין')
, ((SELECT id FROM inserted), 'native, native language', 'from the home country', 'יליד, שפת אם')
, ((SELECT id FROM inserted), 'neither … nor', 'not this and not this', 'לא זה ולא זה')
, ((SELECT id FROM inserted), 'nightmare', 'bad dream', 'סיוט')
, ((SELECT id FROM inserted), 'nonsense', 'something that is silly or stupid', 'שטויות')
, ((SELECT id FROM inserted), 'not believe / understand / hear / say, etc. a word', 'not think something is true', 'לא מאמין/ מבין/ אומר מילה')
, ((SELECT id FROM inserted), 'not until', 'not before', 'לא... עד ש')
, ((SELECT id FROM inserted), 'occupation', 'job', 'עבודה')
, ((SELECT id FROM inserted), 'occupy, occupied', 'fill or use a place or a period of time', 'לתפוס (זמן או מקום)')
, ((SELECT id FROM inserted), 'oil', 'fuel', 'נפט')
, ((SELECT id FROM inserted), 'on the whole', 'in general', 'בגדול,')
, ((SELECT id FROM inserted), 'open, opening', 'start officially', 'פתיחה רשמית')
, ((SELECT id FROM inserted), 'operate, operation', 'surgery', 'לנתח, ניתוח')
, ((SELECT id FROM inserted), 'organ', 'part of an animal', 'איבר פנימי')
, ((SELECT id FROM inserted), 'organization', 'arrangement', 'ארגון')
, ((SELECT id FROM inserted), 'outstanding', 'amazing, exceptional', 'יוצא מן הכלל')
, ((SELECT id FROM inserted), 'part-time', 'part of the full hours', 'חצי משרה')
, ((SELECT id FROM inserted), 'patient, patience', 'able to wait', 'סבלן, סבלנות')
, ((SELECT id FROM inserted), 'peculiar', 'strange', 'מוזר')
, ((SELECT id FROM inserted), 'place', 'at university, in race or competition', 'מקום (ראשון כמו בתחרות)')
, ((SELECT id FROM inserted), 'point', 'exact time/place', 'נקודה (זמן או מקום)')
, ((SELECT id FROM inserted), 'point', 'to hold something so that it faces towards someone or something', 'לכוון')
, ((SELECT id FROM inserted), 'position', 'situation/ location', 'מעמד, מצב')
, ((SELECT id FROM inserted), 'potential, potentially', 'could be in the future', 'פוטנציאל')
, ((SELECT id FROM inserted), 'preference', 'liking something more than something else', 'העדפה')
, ((SELECT id FROM inserted), 'present', 'show or describe to other people', 'להציג (מצגת)')
, ((SELECT id FROM inserted), 'pressure', 'stress, tension', 'לחץ')
, ((SELECT id FROM inserted), 'prime, primary', 'most important, first', 'הכי חשוב')
, ((SELECT id FROM inserted), 'principal', 'main; head of school', 'מנהל בית ספר')
, ((SELECT id FROM inserted), 'promote, promotion', 'to get a better job in your company', 'לקדם, קידום')
, ((SELECT id FROM inserted), 'put up with sth/sb', 'to accept something or someone unpleasant', 'להשלים (עם המציאות)')
, ((SELECT id FROM inserted), 'reach', 'stretch and touch', 'להגיע')
, ((SELECT id FROM inserted), 'reason', 'showing a fair and good judgement', 'הגיון')
, ((SELECT id FROM inserted), 'record', 'store information', 'לתעד, להקליט')
, ((SELECT id FROM inserted), 'reflect, reflection', 'what you see in a mirror', 'לשקף, השתקפות')
, ((SELECT id FROM inserted), 'register, registration', 'sign up, signing up', 'להירשם, רישום')
, ((SELECT id FROM inserted), 'regret', 'feeling of sadness or remorse', 'להתחרט')
, ((SELECT id FROM inserted), 'relate (v), related (adj), relationship (n), connect (v), connected (adj), connection (n)', 'to be connected or associated', 'להיות קשור (פ), קשור (ת ש), קשר (ש''ע)')
, ((SELECT id FROM inserted), 'relax, relaxed', 'calm', 'להירגע, רגוע')
, ((SELECT id FROM inserted), 'remark', 'comment', 'להעיר, הערה')
, ((SELECT id FROM inserted), 'remote', 'far away', 'רחוק')
, ((SELECT id FROM inserted), 'replace, replacement', 'to switch, substitute', 'להחליף, החלפה')
, ((SELECT id FROM inserted), 'rescue', 'to save', 'להציל')
, ((SELECT id FROM inserted), 'respect, respectable', 'to admire because someone has good qualities', 'לכבד, מכובד')
, ((SELECT id FROM inserted), 'retire, retired, retirement', 'end one''s career', 'לצאת לפסניה, יצא לפנסיה, פנסיה')
, ((SELECT id FROM inserted), 'right', 'morally acceptable', 'נכון, צודק')
, ((SELECT id FROM inserted), 'role', 'function, purpose', 'תפקיד')
, ((SELECT id FROM inserted), 'room', 'space', 'מקום')
, ((SELECT id FROM inserted), 'rough, roughly', 'not exact; not exactly', 'בערך')
, ((SELECT id FROM inserted), 'rule', 'law, regulation', 'חוק, כלל')
, ((SELECT id FROM inserted), 'rule, ruler', 'reign, govern', 'לשלוט/ שליטה, מושל')
, ((SELECT id FROM inserted), 'run', 'to operate, manage a business', 'לנהל')
, ((SELECT id FROM inserted), 'rush', 'to go quickly', 'למהר')
, ((SELECT id FROM inserted), 'satisfy', 'to please', 'לספק, להשביע, לרצות')
, ((SELECT id FROM inserted), 'satisfaction, satisfactory, satisfied', 'a pleasant feeling, good enough, pleased', 'שביעות רצון, משביע, מרוצה')
, ((SELECT id FROM inserted), 'scale', 'size, ratio', 'קנה מידה')
, ((SELECT id FROM inserted), 'scene, scenery', 'in play, film etc', 'סצנה')
, ((SELECT id FROM inserted), 'schedule', 'list of planned activities and times', 'מערכת שעות')
, ((SELECT id FROM inserted), 'sensitive, sensitivity', 'quick to notice or feel', 'רגיש, רגישות')
, ((SELECT id FROM inserted), 'service, serve', 'government system, department (n) / do work that helps society (e.g., army or government) (v)', 'שירות, לשרת (בצבא למשל)')
, ((SELECT id FROM inserted), 'set', 'arrange/fixed, established', 'לקבוע, קבוע')
, ((SELECT id FROM inserted), 'setting, set', 'book/film etc.; story; film/play', 'רקע, תפאורה')
, ((SELECT id FROM inserted), 'shortly', 'soon', 'עוד מעט')
, ((SELECT id FROM inserted), 'shut (something) down or shut down (something)', 'turn off', 'לכבות')
, ((SELECT id FROM inserted), 'similarity', 'being almost the same', 'דימיון (בין דברים דומים)')
, ((SELECT id FROM inserted), 'slow (something/somebody) down / up or slow down/up ((something/somebody)', 'go more slowly', 'להאט')
, ((SELECT id FROM inserted), 'so-called', 'known as', 'כביכול, לכאורה')
, ((SELECT id FROM inserted), 'society, social', '1 (n) a large number of people and the way they live 2 (adj) living and communicating with others', 'חברה, חברתי')
, ((SELECT id FROM inserted), 'sooner or later', 'eventually', 'בסופו של דבר (במוקדם או במאוחר)')
, ((SELECT id FROM inserted), 'spectacular', 'exciting to look at', 'מרהיב')
, ((SELECT id FROM inserted), 'speech', 'formal talk', 'נאום')
, ((SELECT id FROM inserted), 'spoil', 'to ruin', 'לקלקל')
, ((SELECT id FROM inserted), 'start (sth) off or start off (sth)', 'to begin', 'להתחיל')
, ((SELECT id FROM inserted), 'style', 'individual way, method etc.; in art, literature, music, etc.', 'סגנון')
, ((SELECT id FROM inserted), 'sum up (something/somebody) or sum (something/somebody) up', 'describe the important facts', 'לסכם')
, ((SELECT id FROM inserted), 'summary', 'a short description of the main facts', 'סיכום')
, ((SELECT id FROM inserted), 'support, supporter', 'help and encourage, especially financially', 'לתמוך, תומך')
, ((SELECT id FROM inserted), 'survive', 'to stay alive', 'לשרוד')
, ((SELECT id FROM inserted), 'survival, survivor', 'staying alive', 'הישרדות, ניצול (שורד)')
, ((SELECT id FROM inserted), 'take into account sth', 'to consider', 'לקחת בחשבון')
, ((SELECT id FROM inserted), 'take part', 'participate', 'לקחת חלק')
, ((SELECT id FROM inserted), 'take place', 'happen', 'להתרחש')
, ((SELECT id FROM inserted), 'take the/this opportunity to do sth', 'to do something when it is available', 'לנצל הזדמנות')
, ((SELECT id FROM inserted), 'take sb/sth seriously', 'to relate to in a serious way', 'לקחת ברצינות')
, ((SELECT id FROM inserted), 'take/accept/claim responsibility for sth', 'being willing to be in charge of something', 'לקבל אחריות')
, ((SELECT id FROM inserted), 'the headlines', 'the title of a newspaper article', 'כותרות (בעיתון)')
, ((SELECT id FROM inserted), 'the heart of sth', 'the main part', 'לב העניין')
, ((SELECT id FROM inserted), 'the main thing', 'the most important part', 'הדבר העיקרי')
, ((SELECT id FROM inserted), 'the reality/realities of sth', 'the truth', 'המציאות')
, ((SELECT id FROM inserted), 'theme', 'main subject or idea', 'הנושא/ המוטיב העיקרי')
, ((SELECT id FROM inserted), 'to', 'toward, until', 'אל, עד')
, ((SELECT id FROM inserted), 'to start with', 'to begin with', 'בתור התחלה')
, ((SELECT id FROM inserted), 'treasure', 'something valuable', 'אוצר')
, ((SELECT id FROM inserted), 'try', 'attempt', 'ניסיון')
, ((SELECT id FROM inserted), 'turn', 'chance, opportunity', 'תור')
, ((SELECT id FROM inserted), 'uncomfortable', 'not pleasant', 'לא נוח')
, ((SELECT id FROM inserted), 'underneath', 'under or below', 'מתחת')
, ((SELECT id FROM inserted), 'understand', 'know feelings; sympathy; sympathetic', 'להבין מישהו, להיות אמפתי')
, ((SELECT id FROM inserted), 'understanding', 'sympathy', 'הבנה, אמפתיה')
, ((SELECT id FROM inserted), 'undo', 'cancel something that was done', 'לבטל')
, ((SELECT id FROM inserted), 'unemployed', 'without a job', 'מובטל')
, ((SELECT id FROM inserted), 'unexpected', 'not known that it would happen', 'לא צפוי')
, ((SELECT id FROM inserted), 'up-to-date', 'new, modern', 'מעודכן')
, ((SELECT id FROM inserted), 'urgent, urgently', 'must be done immediately', 'דחוף, באופן דחוף')
, ((SELECT id FROM inserted), 'use up something or use something up', 'use something until there is none left', 'לגמור הכל')
, ((SELECT id FROM inserted), 'virtual reality', 'digital images that make a person feel they are inside it', 'מציאות מדומה')
, ((SELECT id FROM inserted), 'vowel', 'the letters a, e, i, o, u', 'אות ניקוד')
, ((SELECT id FROM inserted), 'waste', 'use too much', 'לבזבז, בזבוז')
, ((SELECT id FROM inserted), 'wealth, wealthy', 'richness, rich', 'עושר, עשיר')
, ((SELECT id FROM inserted), 'welcome', 'support, encourage; pleasing', 'לקבל בברכה')
, ((SELECT id FROM inserted), 'wherever', 'in any place', 'כל מקום שהוא')
;
