INSERT INTO exams (id, name) VALUES (1, 'Exam 3');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (1, 1, 'reliable', 'trustworthy', 'אמין');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (2, 1, 'rely on/upon sb/sth', 'help, depend on, need someone for support', 'להסתמך על, להיות תלוי ב, להזדקק ל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (3, 1, 'request', 'asking for something', 'לבקש, בקשה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (4, 1, 'research', 'a study, a scientific investigation', 'לחקור, מחקר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (5, 1, 'researcher', 'scientist', 'חוקר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (6, 1, 'result', 'what happens in the end', 'תוצאה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (7, 1, 'resulting', 'cause', 'מביא לתוצאה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (8, 1, 'review', 'go over and give opinion/ opinion', 'לסקור, סקירה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (9, 1, 'revise', 'review, study over and make changes', 'לחזור');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (10, 1, 'revision', 'review', 'חזרה על חומר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (11, 1, 'risk', 'danger/ chance', 'סכנה, סיכון');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (12, 1, 'run out of', 'finish', 'אזל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (13, 1, 'rural', 'in the countryside, out of the city', 'כפרי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (14, 1, 'salary', 'money earned from work', 'משכורת');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (15, 1, 'sample', 'a small part, example', 'מדגם, דוגמית');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (16, 1, 'seldom', 'infrequently, not often', 'לעיתים רחוקות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (17, 1, 'sense', 'reason, good judgement', 'הגיון');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (18, 1, 'sensible', 'logical, smart', 'הגיוני, חכם');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (19, 1, 'set up', 'put in the right place, begin', 'להכין, להקים');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (20, 1, 'set out', 'begin a journey, present', 'לצאת למסע, להציג');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (21, 1, 'significant', 'large amount, important, meaningful', 'משמעותי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (22, 1, 'significantly', 'in a big or meaningful way', 'באופן משמעותי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (23, 1, 'significance', 'meaning, importance', 'משמעות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (24, 1, 'skilled', 'has the ability to do something well', 'מוכשר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (25, 1, 'skillful', 'has an impressive ability', 'מוכשר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (26, 1, 'slight', 'a small amount', 'דק, קטן');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (27, 1, 'slightly', 'a little bit', 'בקצת');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (28, 1, 'specialist', 'someone with specific skills', 'מומחה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (29, 1, 'specialize', 'to study something specific', 'להתמחות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (30, 1, 'specific', 'certain, exact', 'ספציפי, מסויים');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (31, 1, 'specifically', 'especially', 'באופן ספציפי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (32, 1, 'specify', 'to say exactly, in detail', 'לפרט');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (33, 1, 'still', 'despite everything', 'עדיין (למרות)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (34, 1, 'structure', 'shape, design', 'מבנה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (35, 1, 'study', 'examine, look at, learn; research', 'ללמוד, מחקר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (36, 1, 'supposed', 'should', 'אמור');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (37, 1, 'surface', 'top or outer layer', 'פני השטח');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (38, 1, 'take advantage of sth', 'make use of something', 'לנצל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (39, 1, 'thanks to sb/sth', 'because of', 'הודות ל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (40, 1, 'theoretical', 'the idea of something', 'באופן תאורטי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (41, 1, 'theory', 'an idea', 'תאוריה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (42, 1, 'throw away/out sth or throw sth away/out', 'put in the garbage, dispose of', 'לזרוק(לפח)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (43, 1, 'transport', 'move from place to place', 'שינוע, לשנע');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (44, 1, 'transportation', 'a way of taking something or someone from place to place', 'תחבורה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (45, 1, 'trash', 'garbage', 'זבל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (46, 1, 'treatment', 'dealing with, medical care', 'טיפול');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (47, 1, 'unfortunate', 'bad, unlucky', 'לא טוב, מזל רע');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (48, 1, 'unfortunately', 'sadly', 'לצערנו');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (49, 1, 'unhealthy', 'not healthy', 'לא בריא');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (50, 1, 'unique', 'special, one of a kind', 'ייחודי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (51, 1, 'united', 'together, as one', 'מאוחד');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (52, 1, 'unite', 'to combine', 'לאחד');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (53, 1, 'unity', 'being together as one', 'איחוד');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (54, 1, 'universal', 'true all over the world', 'אונברסלי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (55, 1, 'universe', 'everything that exists', 'יקום');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (56, 1, 'unknown', 'not known', 'לא יודע');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (57, 1, 'unlike', 'different from', 'לא דומה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (58, 1, 'unlikely', 'improbable', 'לא סביר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (59, 1, 'urban', 'related to a city', 'עירוני');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (60, 1, 'variation', 'difference', 'הבדל, מגוון');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (61, 1, 'vary', 'to change', 'לגוון');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (62, 1, 'view', 'a scene you can see', 'נוף');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (63, 1, 'viewer', 'people who watch', 'הצופה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (64, 1, 'visible', 'can be seen', 'ניתן לראות אותו');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (65, 1, 'vision', 'dream, hope, idea, sight', 'חזון');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (66, 1, 'volume', 'amount', 'כמות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (67, 1, 'whom', '(used instead of ''who'' as the object of a verb)', 'מי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (68, 1, 'wildlife', 'wild animals', 'חיות בר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (69, 1, 'within', 'a limit of time or distance', 'תוך (זמן או מקום)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (70, 1, 'worthwhile', 'valuable, worth spending time or money on it', 'שווה, כדאי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (71, 1, 'would', '(used as the past form of ''will'' to talk about what someone said or thought)', 'היה עושה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (72, 1, 'above', 'in a higher place', 'מעל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (73, 1, 'account', 'a report', 'דין וחשבון');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (74, 1, 'acquire', 'to get', 'להשיג, לרכוש');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (75, 1, 'acquisition', 'getting', 'רכישה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (76, 1, 'age', 'period of history', 'עידן');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (77, 1, 'aged', 'old', 'זקן');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (78, 1, 'agriculture', 'farming', 'חקלאות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (79, 1, 'agricultural', 'related to farming', 'חקלאי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (80, 1, 'all of a sudden', 'suddenly', 'לפתע');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (81, 1, 'altogether', 'entirely, completely', 'סך הכל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (82, 1, 'anxious', 'worried, concerned', 'מוטרד');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (83, 1, 'anxiety', 'a condition of feeling uneasy or worried about what may happen', 'חרדה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (84, 1, 'apparent', 'clearly visible, obvious', 'נראה לעיין');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (85, 1, 'apparently', 'obviously, seemingly', 'כנראה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (86, 1, 'appropriate', 'suitable', 'הולם');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (87, 1, 'atmosphere', 'a thin layer of gases surrounding Earth', 'אטמוספרה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (88, 1, 'automatically', 'gets done without a person''s deliberate control', 'באופן אוטומטי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (89, 1, 'bad', 'rotting', 'רקוב');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (90, 1, 'be in charge', 'take control, be the leader', 'להיות אחראי על');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (91, 1, 'be situated in/on/by, etc', 'to be in a particular place', 'להיות ממוקם ב');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (92, 1, 'behind', 'slower', 'מאחור');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (93, 1, 'believe in something', 'to think that sth is good or right', 'להאמין ב');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (94, 1, 'blame', 'to say or think that a person or thing is responsible for something bad that has happened', 'להאשים');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (95, 1, 'block', 'not to let pass or see', 'לחסום');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (96, 1, 'brilliant', 'very intelligent', 'מבריק');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (97, 1, 'bring up somebody or bring somebody up', 'to care for a child until it is an adult', 'לגדל (ילד)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (98, 1, 'calculate', 'to work out by using math', 'לחשב');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (99, 1, 'calculator', 'a small machine that is used for math', 'מחשבון');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (100, 1, 'clothing', 'things you wear', 'ביגוד');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (101, 1, 'competitive', 'wanting to win or to be more successful than other people', 'תחרותי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (102, 1, 'competitor', 'one who competes against others', 'המתחרה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (103, 1, 'contemporary', 'current, modern, from the same time', 'בן זמננו');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (104, 1, 'contest', 'competition', 'תחרותי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (105, 1, 'continent', 'one of the seven large landmasses on the earth', 'יבשת');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (106, 1, 'copy', 'single one (book, paper)', 'עותק');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (107, 1, 'criterion', 'a standard of judgement', 'מדד');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (108, 1, 'cut down sth or cut sth down', 'to reduce', 'לצמצם');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (109, 1, 'decade', 'a period of 10 years', 'עשור');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (110, 1, 'declaration', 'a public statement', 'הצהרה,הכרזה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (111, 1, 'declare', 'to make known, to state publically', 'להצהיר, להכריז');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (112, 1, 'degree', 'qualification/ unit of measurement', 'מידה, מעלה, תואר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (113, 1, 'deliver', 'to take [something] to a person or place', 'לבצע משלוח');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (114, 1, 'demanding', 'needing a lot of your time, attention, or effort', 'תובעני');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (115, 1, 'detect', 'to discover', 'לגלות, להבחין');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (116, 1, 'determine', 'to decide', 'לקבוע להחליט');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (117, 1, 'differ', 'to disagree', 'לחלוק על');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (118, 1, 'differ', 'to vary widely', 'להיות שונה');
INSERT INTO exams (id, name) VALUES (2, 'Exam 4');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (119, 2, 'disappointed', 'unhappy about the way something turned out', 'מאוכזב');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (120, 2, 'disappointment', 'feeling of sadness because something is not as good as expected', 'אכזבה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (121, 2, 'divide', 'to separate into two or more parts', 'לחלק');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (122, 2, 'division', 'the act or process of dividing', 'חלוקה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (123, 2, 'domestic', 'Having to do with the home or home country', 'של בית');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (124, 2, 'done', 'finished or completed', 'עשוי, גמור');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (125, 2, 'double', 'twice as much', 'כפול');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (126, 2, 'economical', 'careful about spending money or using resources', 'חסכני');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (127, 2, 'editor', 'the head of a news organization; person who chooses the articles that will be printed each day', 'עורך (עיתון)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (128, 2, 'either way', 'in both cases', 'בכל מקרה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (129, 2, 'element', 'A pure substance made of only one kind of atom', 'יסוד (בטבע)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (130, 2, 'emerge', 'to come out; appear', 'לבצבץ');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (131, 2, 'emotion', 'the feeling that is produced in response to life experiences', 'רגש');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (132, 2, 'emotional', 'showing strong feelings', 'רגשני');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (133, 2, 'exception', 'something that does not fit into a general rule', 'יוצא מן הכלל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (134, 2, 'exchange', 'giving up something in order to receive something else', 'חילופין');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (135, 2, 'expected', 'to think something will probably happen', 'צפוי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (136, 2, 'expedition', 'A long journey by a group to explore or do battle', 'משלחת מחקרית');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (137, 2, 'at the expense of', 'at the cost of', 'על חשבון');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (138, 2, 'expense', 'the cost of goods or services', 'הוצאה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (139, 2, 'export', 'send (goods or services) to another country for sale.', 'לייצא');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (140, 2, 'expression', 'word or phrase', 'ביטוי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (141, 2, 'extend', 'to hold out, to stretch, to offer', 'להעניק');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (142, 2, 'extreme', 'the furthest or highest degree of something', 'קיצוני');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (143, 2, 'farther/further', 'more far', 'רחוק יותר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (144, 2, 'fed up', 'bored or frustrated and unhappy', 'נמאס (לו)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (145, 2, 'fetch', 'to go after and bring back', 'ללכת להביא משהו/ מישהו');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (146, 2, 'final, semi-final', 'last, end', 'סופי, גמר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (147, 2, 'fit, fitness', 'healthy', 'בכושר, כושר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (148, 2, 'generation', 'generation', 'דור');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (149, 2, 'genuine', 'real, authentic', 'אמיתי, מקורי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (150, 2, 'get rid of something', 'make something go away', 'להיפטר ממשהו');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (151, 2, 'get sth wrong', 'make a mistake', 'לטעות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (152, 2, 'get worse', 'become bad', 'להתדרדר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (153, 2, 'give away sth or give sth away', 'לתת משהו למישהו', 'לתת משהו למישהו');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (154, 2, 'go out', 'leave', 'לצאת');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (155, 2, 'hidden', 'not possible to see', 'מחובא');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (156, 2, 'highlight', 'show that something is important', 'להדגיש');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (157, 2, 'historian', 'someone who studies history', 'היסטורין');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (158, 2, 'historic', 'of great importance', 'היסטורי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (159, 2, 'identical', 'the same', 'זהה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (160, 2, 'immigration', 'moving from one country to another', 'הגירה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (161, 2, 'immigrant', 'a person who moves from one country to another', 'מהגר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (162, 2, 'import', 'bring products into a country', 'לייבא');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (163, 2, 'import', 'the act of bringing products into a country', 'ייבוא');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (164, 2, 'impress', 'make someone admire you', 'להרשים');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (165, 2, 'impression', 'an idea or opinion about someone or something', 'רושם');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (166, 2, 'impressive', 'causing people to admire it', 'מרשים');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (167, 2, 'incredible', 'amazing', 'לא יאומן');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (168, 2, 'incredibly', 'in an amazing way', 'באופן מדהים');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (169, 2, 'indoors', 'inside a building', 'בתוך הבית');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (170, 2, 'infection', 'get sick in a way that spreads', 'זיהום');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (171, 2, 'input', 'opinion', 'דעה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (172, 2, 'inside', 'feeling', 'בפנים (ברגש)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (173, 2, 'interact', 'behave and respond', 'לפעול בצורה הדדית');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (174, 2, 'interaction', 'communication', 'אינטראקציה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (175, 2, 'interpret', 'understand something in your own way', 'לפרש');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (176, 2, 'interrupt', 'stop from speaking', 'להפריע, לקטוע');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (177, 2, 'interruption', 'stopping from speaking', 'הפרעה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (178, 2, 'involvement', 'the act of taking part in something', 'מעורבות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (179, 2, 'involved', 'being part of something', 'מעורב');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (180, 2, 'involve', 'to include', 'לערב');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (181, 2, 'issue', 'topic, problem', 'נושא, סוגיה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (182, 2, 'it looks like/as if/as though', 'it seems that', 'נראה ש...');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (183, 2, 'jam, traffic jam', 'something that is stuck', 'פקק (תנועה)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (184, 2, 'journalist', 'a writer for a newspaper', 'עיתונאי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (185, 2, 'judgment', 'The act of judging people and their actions', 'שיפוט');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (186, 2, 'just as bad / good / tall / clever, etc (as sb/sth)', 'bad/good/tall/clever, etc. in the same way', 'רע/טוב/גבוה/פיקח וכו באותה מידה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (187, 2, 'just', 'fair', 'צודק');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (188, 2, 'justice', 'fairness', 'צדק');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (189, 2, 'keen', 'excited about', 'חד/נלהב');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (190, 2, 'keep', 'delay', 'לעכב');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (191, 2, 'kit', 'a set of things', 'ערכה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (192, 2, 'learn', 'remember', 'ללמוד, לזכור');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (193, 2, 'lecture', 'speech/ give a speech', 'הרצאה, להרצות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (194, 2, 'light, in light of', 'illuminate', 'להדליק, לאור...');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (195, 2, 'living', 'to earn money', 'פרנסה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (196, 2, 'logical, logic', 'something the mind can understand', 'הגיוני, הגיון');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (197, 2, 'look forward to something/doing something', 'be excited about something in the future', 'מצפה ל...');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (198, 2, 'lower', 'to make something not as high', 'להנמיך');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (199, 2, 'make sense', 'be logical', 'להיות הגיוני');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (200, 2, 'make up something or make something up, made up of something', 'to include', 'להיות מורכב מ');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (201, 2, 'make up your mind or make your mind up', 'to decide', 'לקבל החלטה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (202, 2, 'mend', 'to fix', 'לתקן');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (203, 2, 'mixture', 'things combined', 'תערובת');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (204, 2, 'monthly', 'every month', 'חודשי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (205, 2, 'mystery, mysterious', 'something that is not understood', 'תעלומה, מסתורי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (206, 2, 'name', 'say the name of, mention', 'לתת שם, לציין');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (207, 2, 'native, native language', 'from the home country', 'יליד, שפת אם');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (208, 2, 'neither … nor', 'not this and not this', 'לא זה ולא זה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (209, 2, 'nightmare', 'bad dream', 'סיוט');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (210, 2, 'nonsense', 'something that is silly or stupid', 'שטויות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (211, 2, 'not believe / understand / hear / say, etc. a word', 'not think something is true', 'לא מאמין/ מבין/ אומר מילה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (212, 2, 'not until', 'not before', 'לא... עד ש');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (213, 2, 'occupation', 'job', 'עבודה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (214, 2, 'occupy, occupied', 'fill or use a place or a period of time', 'לתפוס (זמן או מקום)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (215, 2, 'oil', 'fuel', 'נפט');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (216, 2, 'on the whole', 'in general', 'בגדול,');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (217, 2, 'open, opening', 'start officially', 'פתיחה רשמית');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (218, 2, 'operate, operation', 'surgery', 'לנתח, ניתוח');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (219, 2, 'organ', 'part of an animal', 'איבר פנימי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (220, 2, 'organization', 'arrangement', 'ארגון');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (221, 2, 'outstanding', 'amazing, exceptional', 'יוצא מן הכלל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (222, 2, 'part-time', 'part of the full hours', 'חצי משרה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (223, 2, 'patient, patience', 'able to wait', 'סבלן, סבלנות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (224, 2, 'peculiar', 'strange', 'מוזר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (225, 2, 'place', 'at university, in race or competition', 'מקום (ראשון כמו בתחרות)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (226, 2, 'point', 'exact time/place', 'נקודה (זמן או מקום)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (227, 2, 'point', 'to hold something so that it faces towards someone or something', 'לכוון');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (228, 2, 'position', 'situation/ location', 'מעמד, מצב');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (229, 2, 'potential, potentially', 'could be in the future', 'פוטנציאל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (230, 2, 'preference', 'liking something more than something else', 'העדפה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (231, 2, 'present', 'show or describe to other people', 'להציג (מצגת)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (232, 2, 'pressure', 'stress, tension', 'לחץ');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (233, 2, 'prime, primary', 'most important, first', 'הכי חשוב');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (234, 2, 'principal', 'main; head of school', 'מנהל בית ספר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (235, 2, 'promote, promotion', 'to get a better job in your company', 'לקדם, קידום');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (236, 2, 'put up with sth/sb', 'to accept something or someone unpleasant', 'להשלים (עם המציאות)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (237, 2, 'reach', 'stretch and touch', 'להגיע');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (238, 2, 'reason', 'showing a fair and good judgement', 'הגיון');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (239, 2, 'record', 'store information', 'לתעד, להקליט');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (240, 2, 'reflect, reflection', 'what you see in a mirror', 'לשקף, השתקפות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (241, 2, 'register, registration', 'sign up, signing up', 'להירשם, רישום');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (242, 2, 'regret', 'feeling of sadness or remorse', 'להתחרט');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (243, 2, 'relate (v), related (adj), relationship (n), connect (v), connected (adj), connection (n)', 'to be connected or associated', 'להיות קשור (פ), קשור (ת ש), קשר (ש''ע)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (244, 2, 'relax, relaxed', 'calm', 'להירגע, רגוע');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (245, 2, 'remark', 'comment', 'להעיר, הערה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (246, 2, 'remote', 'far away', 'רחוק');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (247, 2, 'replace, replacement', 'to switch, substitute', 'להחליף, החלפה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (248, 2, 'rescue', 'to save', 'להציל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (249, 2, 'respect, respectable', 'to admire because someone has good qualities', 'לכבד, מכובד');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (250, 2, 'retire, retired, retirement', 'end one''s career', 'לצאת לפסניה, יצא לפנסיה, פנסיה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (251, 2, 'right', 'morally acceptable', 'נכון, צודק');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (252, 2, 'role', 'function, purpose', 'תפקיד');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (253, 2, 'room', 'space', 'מקום');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (254, 2, 'rough, roughly', 'not exact; not exactly', 'בערך');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (255, 2, 'rule', 'law, regulation', 'חוק, כלל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (256, 2, 'rule, ruler', 'reign, govern', 'לשלוט/ שליטה, מושל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (257, 2, 'run', 'to operate, manage a business', 'לנהל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (258, 2, 'rush', 'to go quickly', 'למהר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (259, 2, 'satisfy', 'to please', 'לספק, להשביע, לרצות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (260, 2, 'satisfaction, satisfactory, satisfied', 'a pleasant feeling, good enough, pleased', 'שביעות רצון, משביע, מרוצה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (261, 2, 'scale', 'size, ratio', 'קנה מידה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (262, 2, 'scene, scenery', 'in play, film etc', 'סצנה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (263, 2, 'schedule', 'list of planned activities and times', 'מערכת שעות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (264, 2, 'sensitive, sensitivity', 'quick to notice or feel', 'רגיש, רגישות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (265, 2, 'service, serve', 'government system, department (n) / do work that helps society (e.g., army or government) (v)', 'שירות, לשרת (בצבא למשל)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (266, 2, 'set', 'arrange/fixed, established', 'לקבוע, קבוע');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (267, 2, 'setting, set', 'book/film etc.; story; film/play', 'רקע, תפאורה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (268, 2, 'shortly', 'soon', 'עוד מעט');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (269, 2, 'shut (something) down or shut down (something)', 'turn off', 'לכבות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (270, 2, 'similarity', 'being almost the same', 'דימיון (בין דברים דומים)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (271, 2, 'slow (something/somebody) down / up or slow down/up ((something/somebody)', 'go more slowly', 'להאט');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (272, 2, 'so-called', 'known as', 'כביכול, לכאורה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (273, 2, 'society, social', '1 (n) a large number of people and the way they live 2 (adj) living and communicating with others', 'חברה, חברתי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (274, 2, 'sooner or later', 'eventually', 'בסופו של דבר (במוקדם או במאוחר)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (275, 2, 'spectacular', 'exciting to look at', 'מרהיב');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (276, 2, 'speech', 'formal talk', 'נאום');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (277, 2, 'spoil', 'to ruin', 'לקלקל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (278, 2, 'start (sth) off or start off (sth)', 'to begin', 'להתחיל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (279, 2, 'style', 'individual way, method etc.; in art, literature, music, etc.', 'סגנון');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (280, 2, 'sum up (something/somebody) or sum (something/somebody) up', 'describe the important facts', 'לסכם');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (281, 2, 'summary', 'a short description of the main facts', 'סיכום');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (282, 2, 'support, supporter', 'help and encourage, especially financially', 'לתמוך, תומך');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (283, 2, 'survive', 'to stay alive', 'לשרוד');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (284, 2, 'survival, survivor', 'staying alive', 'הישרדות, ניצול (שורד)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (285, 2, 'take into account sth', 'to consider', 'לקחת בחשבון');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (286, 2, 'take part', 'participate', 'לקחת חלק');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (287, 2, 'take place', 'happen', 'להתרחש');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (288, 2, 'take the/this opportunity to do sth', 'to do something when it is available', 'לנצל הזדמנות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (289, 2, 'take sb/sth seriously', 'to relate to in a serious way', 'לקחת ברצינות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (290, 2, 'take/accept/claim responsibility for sth', 'being willing to be in charge of something', 'לקבל אחריות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (291, 2, 'the headlines', 'the title of a newspaper article', 'כותרות (בעיתון)');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (292, 2, 'the heart of sth', 'the main part', 'לב העניין');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (293, 2, 'the main thing', 'the most important part', 'הדבר העיקרי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (294, 2, 'the reality/realities of sth', 'the truth', 'המציאות');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (295, 2, 'theme', 'main subject or idea', 'הנושא/ המוטיב העיקרי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (296, 2, 'to', 'toward, until', 'אל, עד');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (297, 2, 'to start with', 'to begin with', 'בתור התחלה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (298, 2, 'treasure', 'something valuable', 'אוצר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (299, 2, 'try', 'attempt', 'ניסיון');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (300, 2, 'turn', 'chance, opportunity', 'תור');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (301, 2, 'uncomfortable', 'not pleasant', 'לא נוח');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (302, 2, 'underneath', 'under or below', 'מתחת');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (303, 2, 'understand', 'know feelings; sympathy; sympathetic', 'להבין מישהו, להיות אמפתי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (304, 2, 'understanding', 'sympathy', 'הבנה, אמפתיה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (305, 2, 'undo', 'cancel something that was done', 'לבטל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (306, 2, 'unemployed', 'without a job', 'מובטל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (307, 2, 'unexpected', 'not known that it would happen', 'לא צפוי');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (308, 2, 'up-to-date', 'new, modern', 'מעודכן');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (309, 2, 'urgent, urgently', 'must be done immediately', 'דחוף, באופן דחוף');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (310, 2, 'use up something or use something up', 'use something until there is none left', 'לגמור הכל');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (311, 2, 'virtual reality', 'digital images that make a person feel they are inside it', 'מציאות מדומה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (312, 2, 'vowel', 'the letters a, e, i, o, u', 'אות ניקוד');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (313, 2, 'waste', 'use too much', 'לבזבז, בזבוז');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (314, 2, 'wealth, wealthy', 'richness, rich', 'עושר, עשיר');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (315, 2, 'welcome', 'support, encourage; pleasing', 'לקבל בברכה');
INSERT INTO words (id, exam_id, word, meaning, translation) VALUES (316, 2, 'wherever', 'in any place', 'כל מקום שהוא');