export const WordBank = [
  { word: "accuse", match: "להאשים" },
  { word: "admit", match: "להודות ב-/ש-" },
  { word: "again (and again)", match: "שוב (ושוב)" },
  { word: "allow", match: "להרשות" },
  { word: "among", match: "בין, מתוך" },
  { word: "apparently", match: "הנראה כפי" },
  { word: "appear", match: "להופיע" },
  { word: "arrange", match: "לסדר, לארגן" },
  { word: "arrangement", match: "סידור" },
  { word: "asleep", match: "ישן" },
  { word: "attach", match: "לצרף" },
  { word: "awake", match: "ער" },
  { word: "basic", match: "בסיסי" },
  { word: "bone", match: "עצם" },
  { word: "bottom", match: "החלק התחתון, קרקעית" },
  { word: "carpentry", match: "נגרות" },
  { word: "cheer (v)", match: "להריע" },
  { word: "claim (v)", match: "לטעון" },
  { word: "cloud", match: "ענן" },
  { word: "complaint", match: "תלונה" },
  { word: "Contact (v)", match: "ליצור קשר" },
  { word: "court (n)", match: "בית משפט" },
  { word: "crazy", match: "משוגע" },
  { word: "create", match: "ליצור" },
  { word: "creativity", match: "יצירתיות" },
  { word: "crowd (n)", match: "קהל, המון" },
  { word: "customer", match: "לקוח" },
  { word: "database", match: "מסד נתונים" },
  { word: "decorate", match: "לקשט" },
  { word: "delay (v)", match: "לדחות" },
  { word: "design (n,v)", match: "לעצב, לתכנן, עיצוב" },
  { word: "enthusiastic", match: "נלהב" },
  { word: "fail", match: "להיכשל" },
  { word: "field", match: "שדה" },
  { word: "fix", match: "לתקן" },
  { word: "follow", match: "לעקוב אחרי, לנהוג לפי" },
  { word: "fool (n,v)", match: "טיפש, לעבוד על, לרמות" },
  { word: "forbid", match: "לאסור" },
  { word: "general", match: "כללי" },
  { word: "habit", match: "הרגל" },
  { word: "hire", match: "לשכור" },
  { word: "homemaker", match: "עקרת בית" },
  { word: "ignore", match: "להתעלם מ" },
  { word: "impress", match: "להרשים" },
  { word: "influence (n)", match: "השפעה" },
  { word: "insist", match: "להתעקש" },
  { word: "invention", match: "המצאה" },
  { word: "jewel", match: "אבן חן" },
  { word: "join", match: "לחבר" },
  { word: "journal", match: "יומן" },
  { word: "last (v)", match: "להימשך" },
  { word: "lead (v)", match: "להנהיג, להוביל" },
  { word: "mainly", match: "בעיקר" },
  { word: "maximum", match: "מקסימום, מירב" },
  { word: "member", match: "חבר (בקבוצה)" },
  { word: "metal (n)", match: "מתכת" },
  { word: "minimum", match: "מינימום" },
  { word: "miss", match: "להתגעגע, לפספס" },
  { word: "negative", match: "שלילי" },
  { word: "notice (v)", match: "להבחין" },
  { word: "noticeable", match: "בולט" },
  { word: "object (n)", match: "חפץ" },
  { word: "observe", match: "להתבונן, לצפות" },
  { word: "obvious", match: "ברור" },
  { word: "occur", match: "לקרות" },
  { word: "official (n)", match: "עובד ציבור, פקיד אחראי" },
  { word: "officially", match: "באופן רשמי" },
  { word: "ordinary", match: "רגיל" },
  { word: "origin", match: "מקור" },
  { word: "original", match: "מקורי" },
  { word: "packaged", match: "ארוז" },
  { word: "partly", match: "באופן חלקי" },
  { word: "photo / photograph", match: "תצלום" },
  { word: "positive", match: "חיובי, צורת החיוב" },
  { word: "powerful", match: "חזק, רב השפעה" },
  { word: "practical", match: "מעשי, פרקטי" },
  { word: "prayer", match: "תפילה" },
  { word: "precious", match: "יקר ערך" },
  { word: "private", match: "פרטי" },
  { word: "program", match: "תוכנית" },
  { word: "rare", match: "נדיר" },
  { word: "rearrange", match: "לארגן מחדש" },
  { word: "register", match: "לרשום, להירשם" },
  { word: "regular", match: "קבוע, רגיל" },
  { word: "regularly", match: "באופן קבוע" },
  { word: "repeat (v)", match: "לחזור על" },
  { word: "repetition", match: "חזרה" },
  { word: "repetitive", match: "חוזר על עצמו" },
  { word: "reply (v)", match: "להשיב" },
  { word: "routine", match: "שיגרה" },
  { word: "ruin", match: "להרוס" },
  { word: "search (v)", match: "לחפש" },
  { word: "sequence", match: "השתלשלות, רצף" },
  { word: "silver (n)", match: "כסף, כסוף" },
  { word: "site", match: "אתר" },
  { word: "specific", match: "מסוים" },
  { word: "spread (v)", match: "להתפשט" },
  { word: "stick (v)", match: "להדביק, להידבק" },
  { word: "succeed", match: "להצליח" },
  { word: "sucker", match: "פראייר, פתי, מטומטם" },
  { word: "thick", match: "עבה" },
  { word: "thin", match: "רזה" },
  { word: "thousand", match: "אלף" },
  { word: "throughout", match: "במשך, לאורך" },
  { word: "training", match: "הכשרה, אימונים" },
  { word: "trick (n)", match: "תחבולה, תעלול" },
  { word: "trivial", match: "מזעזע" },
  { word: "tube", match: "שפורפרת" },
  { word: "typical", match: "טיפוסי" },
  { word: "unique", match: "ייחודי" },
  { word: "use (n)", match: "שימוש" },
  { word: "valuable", match: "יקר ערך" },
  { word: "warning", match: "אזהרה" },
  { word: "wonder (v)", match: "לתהות" },
  { word: "be worth a fortune", match: "שווה הון" },
  { word: "break the rules", match: "להפר את הכללים" },
  { word: "electrical appliance", match: "מכשיר חשמלי" },
  { word: "follow a pattern", match: "לנהוג לפי דפוס קבוע" },
  { word: "get away", match: "להימלט" },
  { word: "get (something) off the ground", match: "להקים משהו" },
  { word: "log on", match: "להיכנס (במחשב)" },
  { word: "make a fortune", match: "לעשות הון" },
  { word: "on purpose", match: "בכוונה" },
  { word: "put off", match: "לדחות" },
  { word: "reach an agreement", match: "להגיע להסכם" },
  { word: "sign up", match: "להירשם" },
  { word: "social network", match: "רשת חברתית" },
  { word: "status symbol", match: "סמל סטטוס (מעמד חברתי)" },
  { word: "take apart", match: "לפרק" },
];
