export const WordDB = [
  { "word": "reliable", "meaning": "trustworthy", "translation": "אמין" },
  { "word": "rely on/upon sb/sth", "meaning": "help, depend on, need someone for support", "translation": "להסתמך על, להיות תלוי ב, להזדקק ל" },
  { "word": "request", "meaning": "asking for something", "translation": "לבקש, בקשה" },
  { "word": "research", "meaning": "a study, a scientific investigation", "translation": "לחקור, מחקר" },
  { "word": "researcher", "meaning": "scientist", "translation": "חוקר" },
  { "word": "result", "meaning": "what happens in the end", "translation": "תוצאה" },
  { "word": "resulting", "meaning": "cause", "translation": "מביא לתוצאה" },
  { "word": "review", "meaning": "go over and give opinion/ opinion", "translation": "לסקור, סקירה" },
  { "word": "revise", "meaning": "review, study over and make changes", "translation": "לחזור" },
  { "word": "revision", "meaning": "review", "translation": "חזרה על חומר" },
  { "word": "risk", "meaning": "danger/ chance", "translation": "סכנה, סיכון" },
  { "word": "run out of", "meaning": "finish", "translation": "אזל" },
  { "word": "rural", "meaning": "in the countryside, out of the city", "translation": "כפרי" },
  { "word": "salary", "meaning": "money earned from work", "translation": "משכורת" },
  { "word": "sample", "meaning": "a small part, example", "translation": "מדגם, דוגמית" },
  { "word": "seldom", "meaning": "infrequently, not often", "translation": "לעיתים רחוקות" },
  { "word": "sense", "meaning": "reason, good judgement", "translation": "הגיון" },
  { "word": "sensible", "meaning": "logical, smart", "translation": "הגיוני, חכם" },
  { "word": "set up", "meaning": "put in the right place, begin", "translation": "להכין, להקים" },
  { "word": "set out", "meaning": "begin a journey, present", "translation": "לצאת למסע, להציג" },
  { "word": "significant", "meaning": "large amount, important, meaningful", "translation": "משמעותי" },
  { "word": "significantly", "meaning": "in a big or meaningful way", "translation": "באופן משמעותי" },
  { "word": "significance", "meaning": "meaning, importance", "translation": "משמעות" },
  { "word": "skilled", "meaning": "has the ability to do something well", "translation": "מוכשר" },
  { "word": "skillful", "meaning": "has an impressive ability", "translation": "מוכשר" },
  { "word": "slight", "meaning": "a small amount", "translation": "דק, קטן" },
  { "word": "slightly", "meaning": "a little bit", "translation": "בקצת" },
  { "word": "specialist", "meaning": "someone with specific skills", "translation": "מומחה" },
  { "word": "specialize", "meaning": "to study something specific", "translation": "להתמחות" },
  { "word": "specific", "meaning": "certain, exact", "translation": "ספציפי, מסויים" },
  { "word": "specifically", "meaning": "especially", "translation": "באופן ספציפי" },
  { "word": "specify", "meaning": "to say exactly, in detail", "translation": "לפרט" },
  { "word": "still", "meaning": "despite everything", "translation": "עדיין (למרות)" },
  { "word": "structure", "meaning": "shape, design", "translation": "מבנה" },
  { "word": "study", "meaning": "examine, look at, learn; research", "translation": "ללמוד, מחקר" },
  { "word": "supposed", "meaning": "should", "translation": "אמור" },
  { "word": "surface", "meaning": "top or outer layer", "translation": "פני השטח" },
  { "word": "take advantage of sth", "meaning": "make use of something", "translation": "לנצל" },
  { "word": "thanks to sb/sth", "meaning": "because of", "translation": "הודות ל" },
  { "word": "theoretical", "meaning": "the idea of something", "translation": "באופן תאורטי" },
  { "word": "theory", "meaning": "an idea", "translation": "תאוריה" },
  { "word": "throw away/out sth or throw sth away/out", "meaning": "put in the garbage, dispose of", "translation": "לזרוק(לפח)" },
  { "word": "transport", "meaning": "move from place to place", "translation": "שינוע, לשנע" },
  { "word": "transportation", "meaning": "a way of taking something or someone from place to place", "translation": "תחבורה" },
  { "word": "trash", "meaning": "garbage", "translation": "זבל" },
  { "word": "treatment", "meaning": "dealing with, medical care", "translation": "טיפול" },
  { "word": "unfortunate", "meaning": "bad, unlucky", "translation": "לא טוב, מזל רע" },
  { "word": "unfortunately", "meaning": "sadly", "translation": "לצערנו" },
  { "word": "unhealthy", "meaning": "not healthy", "translation": "לא בריא" },
  { "word": "unique", "meaning": "special, one of a kind", "translation": "ייחודי" },
  { "word": "united", "meaning": "together, as one", "translation": "מאוחד" },
  { "word": "unite", "meaning": "to combine", "translation": "לאחד" },
  { "word": "unity", "meaning": "being together as one", "translation": "איחוד" },
  { "word": "universal", "meaning": "true all over the world", "translation": "אונברסלי" },
  { "word": "universe", "meaning": "everything that exists", "translation": "יקום" },
  { "word": "unknown", "meaning": "not known", "translation": "לא יודע" },
  { "word": "unlike", "meaning": "different from", "translation": "לא דומה" },
  { "word": "unlikely", "meaning": "improbable", "translation": "לא סביר" },
  { "word": "urban", "meaning": "related to a city", "translation": "עירוני" },
  { "word": "variation", "meaning": "difference", "translation": "הבדל, מגוון" },
  { "word": "vary", "meaning": "to change", "translation": "לגוון" },
  { "word": "view", "meaning": "a scene you can see", "translation": "נוף" },
  { "word": "viewer", "meaning": "people who watch", "translation": "הצופה" },
  { "word": "visible", "meaning": "can be seen", "translation": "ניתן לראות אותו" },
  { "word": "vision", "meaning": "dream, hope, idea, sight", "translation": "חזון" },
  { "word": "volume", "meaning": "amount", "translation": "כמות" },
  { "word": "whom", "meaning": "(used instead of 'who' as the object of a verb)", "translation": "מי" },
  { "word": "wildlife", "meaning": "wild animals", "translation": "חיות בר" },
  { "word": "within", "meaning": "a limit of time or distance", "translation": "תוך (זמן או מקום)" },
  { "word": "worthwhile", "meaning": "valuable, worth spending time or money on it", "translation": "שווה, כדאי" },
  { "word": "would", "meaning": "(used as the past form of 'will' to talk about what someone said or thought)", "translation": "היה עושה" },
  { "word": "above", "meaning": "in a higher place", "translation": "מעל" },
  { "word": "account", "meaning": "a report", "translation": "דין וחשבון" },
  { "word": "acquire", "meaning": "to get", "translation": "להשיג, לרכוש" },
  { "word": "acquisition", "meaning": "getting", "translation": "רכישה" },
  { "word": "age", "meaning": "period of history", "translation": "עידן" },
  { "word": "aged", "meaning": "old", "translation": "זקן" },
  { "word": "agriculture", "meaning": "farming", "translation": "חקלאות" },
  { "word": "agricultural", "meaning": "related to farming", "translation": "חקלאי" },
  { "word": "all of a sudden", "meaning": "suddenly", "translation": "לפתע" },
  { "word": "altogether", "meaning": "entirely, completely", "translation": "סך הכל" },
  { "word": "anxious", "meaning": "worried, concerned", "translation": "מוטרד" },
  { "word": "anxiety", "meaning": "a condition of feeling uneasy or worried about what may happen", "translation": "חרדה" },
  { "word": "apparent", "meaning": "clearly visible, obvious", "translation": "נראה לעיין" },
  { "word": "apparently", "meaning": "obviously, seemingly", "translation": "כנראה" },
  { "word": "appropriate", "meaning": "suitable", "translation": "הולם" },
  { "word": "atmosphere", "meaning": "a thin layer of gases surrounding Earth", "translation": "אטמוספרה" },
  { "word": "automatically", "meaning": "gets done without a person's deliberate control", "translation": "באופן אוטומטי" },
  { "word": "bad", "meaning": "rotting", "translation": "רקוב" },
  { "word": "be in charge", "meaning": "take control, be the leader", "translation": "להיות אחראי על" },
  { "word": "be situated in/on/by, etc", "meaning": "to be in a particular place", "translation": "להיות ממוקם ב" },
  { "word": "behind", "meaning": "slower", "translation": "מאחור" },
  { "word": "believe in something", "meaning": "to think that sth is good or right", "translation": "להאמין ב" },
  { "word": "blame", "meaning": "to say or think that a person or thing is responsible for something bad that has happened", "translation": "להאשים" },
  { "word": "block", "meaning": "not to let pass or see", "translation": "לחסום" },
  { "word": "brilliant", "meaning": "very intelligent", "translation": "מבריק" },
  { "word": "bring up somebody or bring somebody up", "meaning": "to care for a child until it is an adult", "translation": "לגדל (ילד)" },
  { "word": "calculate", "meaning": "to work out by using math", "translation": "לחשב" },
  { "word": "calculator", "meaning": "a small machine that is used for math", "translation": "מחשבון" },
  { "word": "clothing", "meaning": "things you wear", "translation": "ביגוד" },
  { "word": "competitive", "meaning": "wanting to win or to be more successful than other people", "translation": "תחרותי" },
  { "word": "competitor", "meaning": "one who competes against others", "translation": "המתחרה" },
  { "word": "contemporary", "meaning": "current, modern, from the same time", "translation": "בן זמננו" },
  { "word": "contest", "meaning": "competition", "translation": "תחרותי" },
  { "word": "continent", "meaning": "one of the seven large landmasses on the earth", "translation": "יבשת" },
  { "word": "copy", "meaning": "single one (book, paper)", "translation": "עותק" },
  { "word": "criterion", "meaning": "a standard of judgement", "translation": "מדד" },
  { "word": "cut down sth or cut sth down", "meaning": "to reduce", "translation": "לצמצם" },
  { "word": "decade", "meaning": "a period of 10 years", "translation": "עשור" },
  { "word": "declaration", "meaning": "a public statement", "translation": "הצהרה,הכרזה" },
  { "word": "declare", "meaning": "to make known, to state publically", "translation": "להצהיר, להכריז" },
  { "word": "degree", "meaning": "qualification/ unit of measurement", "translation": "מידה, מעלה, תואר" },
  { "word": "deliver", "meaning": "to take [something] to a person or place", "translation": "לבצע משלוח" },
  { "word": "demanding", "meaning": "needing a lot of your time, attention, or effort", "translation": "תובעני" },
  { "word": "detect", "meaning": "to discover", "translation": "לגלות, להבחין" },
  { "word": "determine", "meaning": "to decide", "translation": "לקבוע להחליט" },
  { "word": "differ", "meaning": "to disagree", "translation": "לחלוק על" },
  { "word": "differ", "meaning": "to vary widely", "translation": "להיות שונה" }
]
